### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by MineshS** [episerver/cms-saas-vercel-demo#17]
Upon re-factoring the codebase to reference NPM Packages we are seeing the following errors when trying to navigate to a page 

` ⨯ unhandledRejection: TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at RouteResolver.convertResponse (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-graph-client/dist/services/routing/index.js:123:18)
    at RouteResolver.getContentInfoByPath (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-graph-client/dist/services/routing/index.js:63:21)     
    at async Module.generateMetadata (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-cms-nextjs/dist/cms-page/page.js:56:27) {
  code: 'ERR_INVALID_URL',
  input: '/en/articles/article-6/'
}`

`Unable to convert {"path":"/en/articles/article-6","locale":{"name":"en"},"contentLink":{"id":221,"workId":516,"guidValue":"f0df2cb1-ad88-414e-9e81-6bf97fe35c73"},"name":"Article 6","contentType":["Page","ArticleDetailPage","Content"],"slug":"article-6","changed":"2024-04-28T13:29:31Z","published":"2024-04-28T13:29:31Z","siteId":"","url":"/en/articles/article-6/"} to Route TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at RouteResolver.convertResponse (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-graph-client/dist/services/routing/index.js:123:18)
    at RouteResolver.tryConvertResponse (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-graph-client/dist/services/routing/index.js:134:25)      
    at Array.map (<anonymous>)
    at RouteResolver.getRoutes (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-graph-client/dist/services/routing/index.js:42:24)
    at async Object.generateStaticParams (webpack-internal:///(rsc)/../../node_modules/@remkoj/optimizely-cms-nextjs/dist/cms-page/page.js:42:21)
    at async buildParams (D:\DevrootArco\Commerce-Frontend\node_modules\next\dist\build\utils.js:1025:40)
    at async D:\DevrootArco\Commerce-Frontend\node_modules\next\dist\build\utils.js:1042:33
    at async Object.loadStaticPaths (D:\DevrootArco\Commerce-Frontend\node_modules\next\dist\server\dev\static-paths-worker.js:47:16) {
  code: 'ERR_INVALID_URL',
  input: '/en/articles/article-6/'
}`

**Comment by MineshS** [comment]
![image](https://github.com/episerver/cms-saas-vercel-demo/assets/45593010/79651bd6-619f-43a6-9aeb-21811530500f)
